/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrzychodnieRouteImport } from './routes/przychodnie'
import { Route as IndexRouteImport } from './routes/index'

const PrzychodnieRoute = PrzychodnieRouteImport.update({
  id: '/przychodnie',
  path: '/przychodnie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/przychodnie': typeof PrzychodnieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/przychodnie': typeof PrzychodnieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/przychodnie': typeof PrzychodnieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/przychodnie'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/przychodnie'
  id: '__root__' | '/' | '/przychodnie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrzychodnieRoute: typeof PrzychodnieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/przychodnie': {
      id: '/przychodnie'
      path: '/przychodnie'
      fullPath: '/przychodnie'
      preLoaderRoute: typeof PrzychodnieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrzychodnieRoute: PrzychodnieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
